### ISSUE TITLE
az acr login issue 

### ISSUE THREAD

**Issue by RIashfaqahmed** [microsoft/AzureTRE-Deployment#85]
When deploying TRE, if an ACR is being created for the first time, the sleep time is not sufficient to wait until the ACR is fully created and ready for login.

`  for i in ***1..3***; do
    az acr login --name "***" && ec=0 && break || ec=\$? && sleep 10
  done
Error: Process completed with exit code 2.`

**Comment by marrobi** [comment]
We've not seen this before, did the script work when run again?

**Comment by RIashfaqahmed** [comment]
When I re-run **Deploy Azure TRE** workflow, it worked and not raised this error again.

**Comment by jonnyry** [comment]
This occurred for me on the first run also, it appears to be in the second ACR login check - 

`
5s
Run # shellcheck disable=SC2034,SC2015,SC2125
Login Succeeded
/home/runner/work/_temp/6a3de28e-7f9d-4b20-b352-2dfc3b126ef6.sh: line 6: exit: $ec: numeric argument required
Error: Process completed with exit code 2.
`

The second run passes, perhaps because the first login check passes and therefore the second check is no longer executed.

**Comment by marrobi** [comment]
Believe this is due to https://github.com/microsoft/AzureTRE-Deployment/pull/74/files#diff-5a2b3ccde8a4255fb43032fe938e96b572e2bee154824cab96b2027cb6a405c9R222 and need to ensure applied everywhere.

**Comment by tim-allen-ck** [comment]
A fix for this has been applied to the main branch, closing
